---
- name: docker operation using jenkins
  hosts: dev
  user: ansible
  become: true
  connection: ssh

  tasks:

  - name: Pull latest image
    command: docker pull zaidmohammad038/static-web

  - name: Stop existing container
    command: docker rm -f webapp
    ignore_errors: yes

  - name: Run container
    command: docker run -d -p 8085:80 --name webapp zaidmohammad038/static-web
